project_name: gcloc

builds:
  - main: ./cmd/main.go
    binary: gcloc
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

dockers:
  - image_templates:
      - 'joaodanielrufino/gcloc:latest'
      - 'joaodanielrufino/gcloc:{{ .Tag }}'
    dockerfile: goreleaser.dockerfile
