project_name: gcloc

builds:
  - main: ./cmd/gcloc/main.go
    binary: gcloc
    ldflags:
      - -X github.com/JoaoDanielRufino/gcloc/internal/constants.Version={{ .Tag }}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - builds:
      - gcloc
    format_overrides:
      - goos: windows
        format: zip

dockers:
  - image_templates:
      - 'joaodanielrufino/gcloc:latest'
      - 'joaodanielrufino/gcloc:{{ .Tag }}'
    dockerfile: goreleaser.dockerfile
