name: Test CLI

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  unit-tests:
    name: Unit tests   
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]    
    runs-on: ${{ matrix.os }}  
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Run unit tests
      run: make test
